# Copyright (c) 2026 Brothertown Language
name = "snea-editor"
main = "src/backend/worker.py"
compatibility_date = "2024-01-01"
compatibility_flags = ["python_workers"]

[vars]
# In unified architecture, the frontend and backend are on the same domain
BACKEND_URL = "https://snea-editor.michael-conrad.com"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "snea-shoebox"
database_id = "1d51d911-7942-40c6-bf3a-09951d20534e"
