name = "snea-backend"
main = "src/backend/worker.py"
compatibility_date = "2024-01-01"
compatibility_flags = ["python_workers"]

[[d1_databases]]
binding = "DB"
database_name = "snea-shoebox"
database_id = "1d51d911-7942-40c6-bf3a-09951d20534e"
